-- Flyway Migration V1.1
-- Adiciona campos de perfil à tabela SolicitacaoCadastro de forma segura
-- Preserva dados existentes

ALTER TABLE SOLICITACOES_CADASTRO ADD COLUMN FORNECEDOR BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE SOLICITACOES_CADASTRO ADD COLUMN COMPRADOR BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE SOLICITACOES_CADASTRO ADD COLUMN REPRESENTANTE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE SOLICITACOES_CADASTRO ADD COLUMN CLIENTE BOOLEAN DEFAULT FALSE NOT NULL;

-- Log da migração
-- Campos adicionados com sucesso, todos com padrão FALSE
-- Dados existentes preservados
